codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "60...90"

  status:
    project:
      default:
        target: 85%
        threshold: 5%
    patch:
      default:
        target: 85%
        threshold: 5%
    changes: no

  ignore:
    - "code/core/src/main/java/com/adobe/marketing/mobile/ExtensionListener.java"
    - "code/core/src/main/java/com/adobe/marketing/mobile/InvalidInitException.java"
    - "code/core/src/main/java/com/adobe/marketing/mobile/ExtensionUnexpectedError.java"
    - "code/core/src/main/java/com/adobe/marketing/mobile/internal/CoreConstants.kt"
    - "code/core/src/main/java/com/adobe/marketing/mobile/internal/eventhub/EventHubConstants.kt"
    - "code/core/src/phone/java/com/adobe/marketing/mobile/services/ServiceConstants.kt"
    - "code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/LaunchRulesEngineConstants.kt"
    - "code/core/src/main/java/com/adobe/marketing/mobile/LocalNotificationHandler.java"
    - "code/core/src/main/java/com/adobe/marketing/mobile/NotificationDismissalHandler.java"
    - "code/core/src/main/java/com/adobe/marketing/mobile/launch/rulesengine/json/HistoricalCondition.kt"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: no
