#
# Copyright 2023 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: Publish Snapshot

on: 
  workflow_dispatch:
    inputs:
      release-core:
        description: Release Core snapshot
        type: boolean
        default: false

      release-identity:
        description: Release Identity snapshot
        type: boolean
        default: false

      release-lifecycle:
        description: Release Lifecycle snapshot
        type: boolean
        default: false

      release-signal:
        description: Release Signal snapshot
        type: boolean
        default: false

jobs:
  publish-core:
    if: ${{ github.event.inputs.release-core == 'true' }}
    permissions:
        contents: write
    uses: adobe/aepsdk-commons/.github/workflows/android-maven-snapshot.yml@gha-android-3.3.0
    with:
      release-variant: core
    secrets: inherit

  publish-identity:
    if: ${{ github.event.inputs.release-identity == 'true' }}
    permissions:
        contents: write
    uses: adobe/aepsdk-commons/.github/workflows/android-maven-snapshot.yml@gha-android-3.3.0
    with:
      release-variant: identity
    secrets: inherit

  publish-lifecycle:
    if: ${{ github.event.inputs.release-lifecycle == 'true' }}
    permissions:
        contents: write
    uses: adobe/aepsdk-commons/.github/workflows/android-maven-snapshot.yml@gha-android-3.3.0
    with:
      release-variant: lifecycle
    secrets: inherit

  publish-signal:
    if: ${{ github.event.inputs.release-signal == 'true' }}
    permissions:
        contents: write
    uses: adobe/aepsdk-commons/.github/workflows/android-maven-snapshot.yml@gha-android-3.3.0
    with:
      release-variant: signal
    secrets: inherit